asthadeal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'


urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('singl-product/<slug>/', views.single_product, name='single_product'),
    path('confirm-order/', views.confirm_order, name='confirm_order'),
    path('find-items/', views.serach_items, name='search_item')
] 

shop/models.py
from django.db import models
from django.utils.text import slugify
import uuid
# Create your models here.





class Category(models.Model):
    name = models.CharField(max_length=120)
    create_at = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self) -> str:
        return self.name
    
    
class Product(models.Model):
    name = models.CharField(max_length=360)
    slug = models.SlugField(unique=True ,null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quentity = models.IntegerField(default=1)
    regular_price = models.IntegerField(default=1)
    discount_price = models.IntegerField(default=0)
    Product_image = models.ImageField(upload_to='product')
    product_more_image1 = models.ImageField(upload_to='more image', blank=True, null=True)
    product_more_image2 = models.ImageField(upload_to='more image', blank=True, null=True)
    product_more_image3 = models.ImageField(upload_to='more image', blank=True, null=True)
    product_more_image4 = models.ImageField(upload_to='more image', blank=True, null=True)
    video_id = models.URLField(max_length=600, null=True, blank=True)
    is_new = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    product_details = models.TextField()
    
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) + str(uuid.uuid4())
        super(Product, self).save(*args, **kwargs)
    
    
    def __str__(self) -> str:
        return self.name

    
class ProductMoreImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='more image')
    
    
class Order(models.Model):
    items = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    quentity = models.IntegerField(default=1)
    total_price = models.IntegerField()
    delivery_charge = models.IntegerField(default=0)
    customar_name = models.CharField(max_length=260)
    phone_number = models.CharField(max_length=20)
    address = models.TextField()
    location_area = models.CharField(max_length=200)
    is_deliverd = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self) -> str:
        return self.customar_name
    
    

shop/views.py
from django.shortcuts import render, redirect
from .models import Category, Product, Order
from django.contrib import messages
from django.shortcuts import get_object_or_404
# Create your views here.

def get_naviget_item():
    return Category.objects.all()

def home(request):
    search_value = None
    filter_value = request.GET.get('filter-product')
    products = Product.objects.select_related('category')
    feturd_product = products.filter(is_featured=True)
    category = get_naviget_item()
    if filter_value:
        search_value = products.filter(name__icontains=filter_value)
    
    context = {
        'category':category,
        'feturd_product':feturd_product,
        'search_value':search_value
    }

    return render(request, 'home.html', context)


def serach_items(request):
    search_value = None
    category = get_naviget_item()
    products = Product.objects.select_related('category')
    filter_value = request.GET.get('filter-product')
    if filter_value:
        search_value = products.filter(name__icontains=filter_value)
        context = {
            'search_value':search_value,
            'category':category
        }
        return render(request, 'search_item.html', context)
    else:
        return redirect('shop:home')



def shop(request):
    filter_value = request.GET.get('filter')
    product = Product.objects.select_related("category")
    if filter_value:
        category_id = Category.objects.get(name=filter_value)
        product = product.filter(category=category_id)
    else:
        product = product.all().order_by('-id')
    category = get_naviget_item()
    context = {
        'category':category,
        'product':product
    }
    return render(request, 'shop.html', context)


def single_product(request, slug):
    category = get_naviget_item()
    data = get_object_or_404(Product, slug=slug)
    product_category = data.category
    releted_product = Product.objects.filter(category=product_category)
    
    context = {
        'category':category,
        'data':data,
        'releted_product':releted_product
    }
    return render(request, 'single_product.html', context)


def confirm_order(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        delivery_area = request.POST.get('delivery_area')
        slug = request.POST.get('slug')
        quantity = request.POST.get('quantity')
        total_price = request.POST.get('total_price')
        
        print('--------------')
        print(quantity)
        
        items = Product.objects.get(slug=slug)
        
        order_info = Order (
            customar_name = name,
            phone_number = phone,
            address = address,
            location_area = delivery_area,
            items = items,
            quentity = quantity,
            total_price = total_price
        )
        if delivery_area == 'Inside':
            order_info.delivery_charge = 50
        else:
            order_info.delivery_charge = 100
        
        order_info.save()
        messages.success(request, 'Your Order Successfully confirm')
        return redirect('shop:home')
        
    else:
        return redirect('shop:home')

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>
    {% block title_block %}
      Home
    {% endblock title_block %}
  </title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body>
  <div class="hero_area">
    <!-- header section strats -->

    {% include "includ_files/header.html" %}

    <!-- end header section -->
    <!-- slider section -->
    

    <!-- end slider section -->
  </div>
  <!-- end hero area -->


    {% block body %}
      
    {% endblock body %}

  


  {% include "includ_files/footer.html" %}



  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>

templates/includ_files/banner.html
{% load static %}
<section class="slider_section">
    <div class="slider_container">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active ">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-7">
                  <div class="detail-box">
                    <h4>
                      Welcome To Our <br>
                      Gift Shop
                    </h4>
                    <p>
                      Sequi perspiciatis nulla reiciendis, rem, tenetur impedit, eveniet non necessitatibus error distinctio mollitia suscipit. Nostrum fugit doloribus consequatur distinctio esse, possimus maiores aliquid repellat beatae cum, perspiciatis enim, accusantium perferendis.
                    </p>
                    <a href="{% url 'shop:shop' %}">
                      SHOP NOW
                    </a>
                  </div>
                </div>
                <div class="col-md-5 ">
                  <div class="img-box">
                    <img src="https://thumbs.dreamstime.com/b/%D1%81lose-up-portrait-woman-red-lips-fashion-style-make-posing-studio-156533655.jpg" alt="" />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-7">
                  <div class="detail-box">
                    <h4>
                      Welcome To Our <br>
                      Gift Shop
                    </h4>
                    <p>
                      Sequi perspiciatis nulla reiciendis, rem, tenetur impedit, eveniet non necessitatibus error distinctio mollitia suscipit. Nostrum fugit doloribus consequatur distinctio esse, possimus maiores aliquid repellat beatae cum, perspiciatis enim, accusantium perferendis.
                    </p>
                    <a href="">
                      Contact Us
                    </a>
                  </div>
                </div>
                <div class="col-md-5 ">
                  <div class="img-box">
                    <img src="{% static 'images/slider-img.png' %}" alt="" />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-7">
                  <div class="detail-box">
                    <h4>
                      Welcome To Our <br>
                      Gift Shop
                    </h4>
                    <p>
                      Sequi perspiciatis nulla reiciendis, rem, tenetur impedit, eveniet non necessitatibus error distinctio mollitia suscipit. Nostrum fugit doloribus consequatur distinctio esse, possimus maiores aliquid repellat beatae cum, perspiciatis enim, accusantium perferendis.
                    </p>
                    <a href="">
                      Contact Us
                    </a>
                  </div>
                </div>
                <div class="col-md-5 ">
                  <div class="img-box">
                    <img src="{% static 'images/slider-img.png' %}" alt="" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="carousel_btn-box">
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            <span class="sr-only">Previous</span>
          </a>
          <img src="{% static 'images/line.png' %}" alt="" />
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </section>

templates/includ_files/footer.html
<section class="" style="background-color: rgba(0, 0, 0, 0.527);">
    <div class="social_container">
      <div class="social_box">
        <a href="">
          <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
        <a href="">
          <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
        <a href="">
          <i class="fa fa-instagram" aria-hidden="true"></i>
        </a>
        <a href="">
          <i class="fa fa-youtube" aria-hidden="true"></i>
        </a>
      </div>
    </div>
    <div class="info_container ">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3">
            <h6>
              ABOUT US
            </h6>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doLorem ipsum dolor sit amet, consectetur adipiscing elit, sed doLorem ipsum dolor sit amet,
            </p>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="info_form ">
              <h5>
                Newsletter
              </h5>
              <form action="#">
                <input type="email" placeholder="Enter your email">
                <button>
                  Subscribe
                </button>
              </form>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">
            <h6>
              NEED HELP
            </h6>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doLorem ipsum dolor sit amet, consectetur adipiscing elit, sed doLorem ipsum dolor sit amet,
            </p>
          </div>
          <div class="col-md-6 col-lg-3">
            <h6>
              CONTACT US
            </h6>
            <div class="info_link-box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span> Gb road 123 london Uk </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>+01 12345678901</span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span> demo@gmail.com</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- footer section -->
    <footer class=" footer_section">
      <div class="container">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </footer>
    <!-- footer section -->
  </section>

templates/includ_files/header.html
<header class="header_section">
    <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="/">
            <span>
                TRUSTDEAL
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
                <li class="nav-item">
                    <a class="nav-link" href="/">হোম</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:shop' %}">সব প্রোডাক্ট</a>
                </li>
                {% for i in category %}
                <li class="nav-item">
                    <a class="nav-link" href="/shop/?filter={{i.name}}">{{i.name}}</a>
                </li>
                {% endfor %}

            </ul>
            <div class="user_option">
                <!-- <a href="">
                    <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                </a> -->
                <form class="form-inline" method="GET" action="{% url 'shop:search_item' %}">
                    <input type="text" name="filter-product" id="">
                    <button class="btn nav_search-btn border px-3 text-white -ml-4" style="padding: 0.2rem 0; background-color:#6f42c1" type="submit">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        </div>
    </nav>
</header>

templates/search_item.html
{% extends "base.html" %}

{% block title_block %}
shop
{% endblock title_block %}

{% block body %}


<section class="shop_section layout_padding">
    <div class="container">
        <div class="row">
            {% if search_value %}
            {% for i in search_value %}
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="box shadow">
                    <a href="{% url 'shop:single_product' slug=i.slug %}">
                        <div class="img-box product_img">
                            <img src="{{i.Product_image.url}}" style="border-radius: 5px;" alt="No Image Found">
                        </div>
                        <div>
                            <a href="{% url 'shop:single_product' slug=i.slug %}">
                                <h6>
                                    {{i.name|slice:":25"}}...
                                </h6>
                            </a>
                            <h6>
                                Price:
                                {% if i.discount_price == 0 %}
                                <span>
                                    {{i.regular_price}}&#2547;
                                </span>
                                {% else %}
                                <span>
                                    {{i.discount_price}}&#2547;
                                    <del style="color: rgb(88, 88, 88);">{{i.regular_price}}&#2547;</del>
                                </span>
                                {% endif %}
                            </h6>
                        </div>
                        {% if i.is_new %}
                        <div class="new">
                            <span>
                                New
                            </span>
                        </div>
                        {% endif %}
                    </a>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>Opps! sorry no product found with this search value.</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

templates/shop.html
{% extends "base.html" %}

{% block title_block %}
shop
{% endblock title_block %}

{% block body %}


<section class="shop_section layout_padding">
    <div class="container">
        <div class="row">
            {% if product %}
            {% for i in product %}
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="box">
                    <a href="{% url 'shop:single_product' slug=i.slug %}">
                        <div class="img-box product_img">
                            <img src="{{i.Product_image.url}}" alt="">
                        </div>
                        <div>
                            <a href="{% url 'shop:single_product' slug=i.slug %}">
                                <h6>
                                    {{i.name|slice:":25"}}...
                                </h6>
                            </a>
                            <h6>
                                Price:
                                {% if i.discount_price == 0 %}
                                <span>
                                    {{i.regular_price}}&#2547;
                                </span>
                                {% else %}
                                <span>
                                    {{i.discount_price}}&#2547;
                                    <del style="color: rgb(88, 88, 88);">{{i.regular_price}}&#2547;</del>
                                </span>
                                {% endif %}
                            </h6>
                        </div>
                        {% if i.is_new %}
                        <div class="new">
                            <span>
                                New
                            </span>
                        </div>
                        {% endif %}
                    </a>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>Opps! sorry no product found with this releted category.</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

templates/single_product.html
{% extends "base.html" %}

{% block title_block %}
shop
{% endblock title_block %}

{% block body %}

<div class="layout_padding mx-5 ">
    <p>Home > {{data.name}}</p>
    <div class="row">
        <div class="col-12 col-lg-6">
            <div class="img_container border fullImage">
                <img src="{{data.Product_image.url}}" id="imageBox" alt="">
            </div>
            <div class="p-2 smallImage" style="overflow: hidden;">
                <img src="{{data.Product_image.url}}"  onclick="myFunction(this)" alt="">
                <img src="{{data.product_more_image1.url}}"  onclick="myFunction(this)" alt="">
                <img src="{{data.product_more_image2.url}}"  onclick="myFunction(this)" alt="">
                <img src="{{data.product_more_image3.url}}"  onclick="myFunction(this)" alt="">
                <img src="{{data.product_more_image4.url}}"  onclick="myFunction(this)" alt="">
            </div>
        </div>
        <div class="col-12 col-lg-6">
            <div class="mt-5">
                <h4>{{data.name}}</h4>
            </div>
            <div class="pt-2 pb-2">
                {% if data.quentity < 5 %}
                <span class="text-danger">{{data.quentity}} items available</span>
                {% else %}
                {{data.quentity}} items available in stock
                {% endif %}
            </div>
            <div class="price_box pb-4">
                {% if data.discount_price == 0 %}
                <span>
                    <span id="price">{{data.regular_price}}</span>&#2547;
                </span>
                {% else %}
                <span class="d-flex flex-column">
                    <span class="h3 text-primary">&#2547;<span id="price">{{data.discount_price}}</span></span>
                    <span><del style="color: rgb(88, 88, 88);" class="ml-2">{{data.regular_price}}&#2547;</del></span>
                </span>
                {% endif %}
            </div>
            <div class="py-2">
                <label for="exampleInputEmail1">Quantity</label><br>
                <button id="minus_quantity" style="border: none">-</button> <input type="text" style="width: 5rem;text-align:center" value="1" name="" id="quentity" readonly> <button id="increas_quantity" style="border: none">+</button>
            </div>
            <p>
                
                <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">BUY NOW</a>
                <!-- <button class="btn btn-primary" id="add_to_card">Add To Card</button> -->
            </p>
              <div class="row">
                <div class="col">
                  <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div class="card card-body">
                        <form method="POST" action="{% url 'shop:confirm_order' %}">
                            Please fillup this form
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" name="slug" value="{{data.slug}}" hidden readonly><br>
                                <label for="exampleInputEmail1">Quantity</label>
                                <input type="text" class="form-control" name="quantity" value="1" id="item_quantity" readonly>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Totall Price<span class="text-danger h4">*</span></label>
                                <input type="text" class="form-control" name="total_price" value="{% if data.discount_price == 0 %} {{data.regular_price}} {% else %} {{data.discount_price}} {% endif %}" id="item_price" readonly>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Full Name<span class="text-danger h4">*</span></label>
                                <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Full Name" required>
                            </div>
                            <div class="form-group">
                              <label for="exampleInputEmail1">Phone Number<span class="text-danger h4">*</span></label>
                              <input type="text" class="form-control" name="phone" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Phone Number" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Full Address<span class="text-danger h4">*</span></label>
                                <input type="text" class="form-control" name="address" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Full Address" required
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Select Delivery Area<span class="text-danger h4">*</span>(Delivery Charge: Inside Dhaka-50tk, Outside Data-100tk)</label>
                                <select class="form-control" name="delivery_area" id="exampleFormControlSelect1">
                                  <option value="Inside">Inside Dhaka</option>
                                  <option value="Outside">Outside Dhaka</option>
                                </select>
                            </div>
                            <div class="form-group">
                              <label for="exampleInputEmail1">Delivery Charge<span class="text-danger h4">*</span></label>
                              <input type="text" class="form-control" id="dalivery-charge" value="50" name="address" id="exampleInputEmail1" aria-describedby="emailHelp" readonly></div>
                            <button type="submit" class="btn btn-primary">Confirm Order</button>
                          </form>
                    </div>
                  </div>
                </div>
              </div>
            <div class="mt-4">
                <h5>Product Details</h5>
                <p>{{data.product_details}}</p>
            </div>
        </div>
    </div>
    <div class="my-5">
        <h5 class="mt-4">Product Video</h5>
        <iframe allow="fullscreen;" width="300rem" height="200rem" src="{{data.video_id}}">
        </iframe>
    </div>
</div>
<div class="my-5 p-2">
    <h4>Releted Product</h4>
    <div class="owl-carousel owl-theme p-2" style="background-color: aliceblue;">
      {% for i in releted_product %}
        <div class="item">
            <div class="card" style="width: 18rem;">
                <div style="height: 18rem;overflow: hidden;">
                  <img class="card-img-top" src="{{i.Product_image.url}}" height="100%" alt="Card image cap">
                </div>
                <div class="card-body">
                  <a href="{% url 'shop:single_product' slug=i.slug %}">
                    <h6>
                        {{i.name|slice:":25"}}...
                    </h6>
                </a>
                <h6>
                  Price:
                  {% if i.discount_price == 0 %}
                  <span>
                      {{i.regular_price}}&#2547;
                  </span>
                  {% else %}
                  <span>
                      {{i.discount_price}}&#2547;
                      <del style="color: rgb(88, 88, 88);">{{i.regular_price}}&#2547;</del>
                  </span>
                  {% endif %}
              </h6>
                </div>
              </div>
        </div>
      {% endfor %}
    </div>
</div>

{% endblock %}